version: '3.1'
services:
  webapp:
    build: .
    container_name: dotnet-weatherforecast-container
    ports:
      - 8000:80
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    user: "root:root"
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana